using PlatinumPOS.Components;
using PlatinumPOS.Data;
using PlatinumPOS.Services;
using MudBlazor.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.HttpOverrides;
using System;
using System.Net.Http;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

// Add MudBlazor Services
builder.Services.AddMudServices();

// Add HttpClient
builder.Services.AddHttpClient();

// Add Database Context Factory (thread-safe for Blazor Server)
var connectionString = builder.Configuration.GetConnectionString("Default") 
                       ?? "Host=localhost;Database=pos_db;Username=postgres;Password=postgres";
builder.Services.AddDbContextFactory<PosDbContext>(options =>
    options.UseNpgsql(connectionString));

// Register Custom Services
builder.Services.AddScoped<PosSettingsService>();
builder.Services.AddScoped<CartService>();
builder.Services.AddScoped<LicenceClientService>();
builder.Services.AddScoped<CashierSession>();
builder.Services.AddScoped<AnalyticsService>();
builder.Services.AddScoped<ExcelIntegrationService>();

// Running behind nginx (TLS terminated): honour X-Forwarded-* so the app sees real https.
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

var app = builder.Build();

app.UseForwardedHeaders();

// Auto-initialize the database (EnsureCreated seeds models)
using (var scope = app.Services.CreateScope())
{
    try
    {
        var db = scope.ServiceProvider.GetRequiredService<PosDbContext>();
        db.Database.EnsureCreated();
        
        // Ensure new schema changes are applied if the database already existed
        try
        {
            db.Database.ExecuteSqlRaw("ALTER TABLE \"Transactions\" ADD COLUMN \"CardAmount\" numeric NOT NULL DEFAULT 0.0;");
        }
        catch { /* Column may already exist */ }
        
        try
        {
            db.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""AuditLogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Timestamp"" timestamp with time zone NOT NULL,
                    ""CashierName"" character varying(100) NOT NULL,
                    ""Action"" character varying(100) NOT NULL,
                    ""Details"" text NOT NULL,
                    CONSTRAINT ""PK_AuditLogs"" PRIMARY KEY (""Id"")
                );");
        }
        catch { /* Table may already exist */ }

        // Seed Gadget Shop demo data
        GadgetShopSeeder.Seed(db);
    }
    catch (Exception ex)
    {
        app.Logger.LogError(ex, "An error occurred while initializing the database.");
    }
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseAntiforgery();

app.MapStaticAssets();

// Deployment marker for the client-side "new version available" check (wwwroot/version-check.js).
app.MapGet("/app-version", () => Results.Text(PlatinumPOS.Services.AppVersion.Current));

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.Run();
